## PCA

In [54]:
import numpy as np

A =np.random.rand(30,10)
A=A.T
if A.shape[1]>100:
    pca = PCA(5)  # reduce the dimention to 250 for example
    projected = pca.fit_transform(A)
    print(A.shape)
    print(projected.shape)
    pro = projected.T 
    print(pro.shape)
else:
    print('sss')


sss


In [15]:
from sklearn.decomposition import PCA

A =np.random.rand(30,10)
A_1 =A.T
if A_1.shape[1]>200:
    pca = PCA(5)  # reduce the dimension of the data to 250 
    projected = pca.fit_transform(A_1)
    A_1=projected.T
    

In [16]:
A_1.shape

(10, 30)

In [81]:
def PCA_SP(A):
    if A.shape[0]>200:
        A =A.T
        pca = PCA(min(200,A.shape[0]))  # reduce the dimension of the data to 250 
        projected = pca.fit_transform(A)
        A=projected.T
    return A.shape

In [79]:
A =np.random.rand(300,1500)


In [80]:
PCA_SP(A)

(200, 1500)

In [40]:
A.shape[0]

300

## Efficient SP Algorithm

In [35]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

from sklearn.decomposition import PCA


def SP(data, K):
    A = data

    indices = np.random.choice(range(data.shape[1]), K, replace=False)
    indices = indices.astype(int)
    iter = 0

    for iter in range(0, K):
        k = iter % K
        inds = np.delete(np.copy(indices), k)
        A3 = A[:, inds]
        At = A - np.matmul(np.matmul(A3, np.linalg.pinv(np.matmul(np.transpose(A3), A3))),
                           np.matmul(np.transpose(A3), A))
        

        # Compute just the first column from U and V
        svd = TruncatedSVD(n_components=1)
        svd.fit(np.transpose(At))
        # [U, S, V] = np.linalg.svd(At, full_matrices=False)
        # u1 = U[:, 0]
        # v = V[:, 1]
        u = svd.components_.reshape(-1)
        N = np.linalg.norm(At, axis=0)
        N = np.where(N==0, 1, N)
        B = At / N
        B = np.transpose(B)

        Cr = np.abs(np.matmul(B, u))
        # ind = np.argsort(Cr)[::-1]
        # p = ind[0]
        p = np.argsort(Cr)[-1]
        indices[k] = p
    return indices

## NSP Algorithm

In [3]:
from sklearn.decomposition import TruncatedSVD

# A is the matrix of data
# Always set TR=1
# K is the number of samples that we want to choose from the columns of matrix A...
# These samples are the ones that we prune.


def NSP(A,K,TR):
    svd = TruncatedSVD(n_components=TR)
    svd.fit(A.T)
    u = svd.components_.T
    P=np.eye(A.shape[0])-np.matmul(u,np.linalg.pinv(u))
    At=np.matmul(P,A)
    x=(At**2).sum(axis=0)
    ind=np.argsort(-np.asarray(x))
    ind_sel=ind[0:K]
    return ind_sel


In [50]:
import numpy as np
A=np.random.rand(200,64)


In [5]:
num= range(0, 100)


In [36]:



def NSP(A,K,TR=3):
    svd = TruncatedSVD(n_components=TR)
    svd.fit(A.T)
    u = svd.components_.T
    P=np.eye(A.shape[0])-np.matmul(u,np.linalg.pinv(u))
    At=np.matmul(P,A)
    x=(At**2).sum(axis=0)
    ind=np.argsort(-np.asarray(x))
    ind_sel=ind[0:K]
    return ind_sel

def RND(A, K):
    num_col = A.shape[1]
    indices = np.random.choice(range(num_col), K, replace=False)
    return indices




def NewSP(data, K):
    A = data

    indices = np.random.choice(range(data.shape[1]), K, replace=False)
    indices = indices.astype(int)
    iter = 0

    for iter in range(0, K):
        k = iter % K
        inds = np.delete(np.copy(indices), k)
        A3 = A[:, inds]
        At = A - np.matmul(np.matmul(A3, np.linalg.pinv(np.matmul(np.transpose(A3), A3))),
                           np.matmul(np.transpose(A3), A))
        

        # Compute just the first column from U and V
        svd = TruncatedSVD(n_components=1)
        svd.fit(np.transpose(At))
        # [U, S, V] = np.linalg.svd(At, full_matrices=False)
        # u1 = U[:, 0]
        # v = V[:, 1]
        u = svd.components_.reshape(-1)
        N = np.linalg.norm(At, axis=0)
        N = np.where(N==0, 1, N)
        B = At / N
        B = np.transpose(B)

        Cr = np.abs(np.matmul(B, u))
        # ind = np.argsort(Cr)[::-1]
        # p = ind[0]
        p = np.argsort(Cr)[-1]
        indices[k] = p
    seq = [number for number in range(A.shape[1])]
    ind=np.delete(seq,indices)
    return ind
    

In [45]:
A=np.array([[1,2,2],[1,5,2],[2,9,4]])
A

array([[1, 2, 2],
       [1, 5, 2],
       [2, 9, 4]])

In [64]:
SP(A,3)


array([53,  0, 47])

In [60]:
NewSP(A,3)

[ 8 31 63]
[ 0  1  2  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62])

In [27]:
A.shape[1]

64

In [30]:
seq = [number for number in range(A.shape[1])]
    

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63]

In [89]:

import numpy as np
from sklearn.decomposition import TruncatedSVD

from sklearn.decomposition import PCA


def SP(data, K):
    A = data

    indices = np.random.choice(range(data.shape[1]), K, replace=False)
    indices = indices.astype(int)

    for i in range(0, K):
        k = i % K
        inds = np.delete(np.copy(indices), k)
        A3 = A[:, inds]
        At = A - np.matmul(np.matmul(A3, np.linalg.pinv(np.matmul(np.transpose(A3), A3))),
                           np.matmul(np.transpose(A3), A))
        

        # Compute just the first column from U and V
        svd = TruncatedSVD(n_components=1)
        svd.fit(np.transpose(At))
        # [U, S, V] = np.linalg.svd(At, full_matrices=False)
        # u1 = U[:, 0]
        # v = V[:, 1]
        u = svd.components_.reshape(-1)
        N = np.linalg.norm(At, axis=0)
        N = np.where(N==0, 1, N)
        B = At / N
        B = np.transpose(B)

        Cr = np.abs(np.matmul(B, u))
        # ind = np.argsort(Cr)[::-1]
        # p = ind[0]
        p = np.argsort(Cr)[-1]
        indices[k] = p
    return indices

# Applying PCA to reduce the dimension

def PCA_SP(A,K):
    if A.shape[0]>200:
        A =A.T
        pca = PCA(30)  # reduce the dimension of the data  
        projected = pca.fit_transform(A)
        A=projected.T
        print(A.shape)
    return SP(A, K)

In [90]:
A=np.random.rand(300,200)
PCA_SP(A,5)

(30, 200)


array([135, 164,  95,   4, 171])

In [86]:
A.shape

(300, 200)